# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: 'Azure Pipelines'
  VmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: ./src/NopCommerce.sln
      arguments: '--configuration $(BuildConfiguration)'