---
pool:
  name: 'azure pipelines'
  vmImage: ubuntu-22.04

trigger:
  - develop
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'install'
      publishWebProjects: true
      projects: src/NopCommerce.sln

  - task: DotNetCoreCLI@2
    inputs:
      command: 'run and build'
      publishWebProjects: true
      projects: src/NopCommerce.sln

